"""empty message

Revision ID: 51aefeb64115
Revises: c3037827d7f8
Create Date: 2018-01-23 23:07:22.467154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51aefeb64115'
down_revision = 'c3037827d7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_start', sa.DateTime(), nullable=False),
    sa.Column('voting_stop', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configs')
    # ### end Alembic commands ###
