"""empty message

Revision ID: 59eb88d39083
Revises: e699cd62896b
Create Date: 2018-01-26 01:35:17.890031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59eb88d39083'
down_revision = 'e699cd62896b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('salt', sa.String(length=32), nullable=True))
    op.add_column('admin', sa.Column('token', sa.String(length=1024), nullable=True))
    op.create_unique_constraint(None, 'admin', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='unique')
    op.drop_column('admin', 'token')
    op.drop_column('admin', 'salt')
    # ### end Alembic commands ###
