"""empty message

Revision ID: 8196ad283ec4
Revises: aecbde74bb2b
Create Date: 2018-01-24 00:18:10.032236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8196ad283ec4'
down_revision = 'aecbde74bb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'first_name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('first_name2', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
