"""empty message

Revision ID: 915e7dddad23
Revises: 51aefeb64115
Create Date: 2018-01-23 23:13:08.167817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915e7dddad23'
down_revision = '51aefeb64115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('voting_stop2', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configs', 'voting_stop2')
    # ### end Alembic commands ###
