"""empty message

Revision ID: aecbde74bb2b
Revises: 915e7dddad23
Create Date: 2018-01-23 23:15:55.459442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aecbde74bb2b'
down_revision = '915e7dddad23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configs', 'voting_stop2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('voting_stop2', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
