"""empty message

Revision ID: e8c49448939b
Revises: 1be103b404d9
Create Date: 2018-01-23 12:38:35.298304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c49448939b'
down_revision = '1be103b404d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('num_of_votes', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_column('candidates', 'num_of_votes')
    # ### end Alembic commands ###
